# -------------------------------
# Stage 1: Build the application
# -------------------------------
FROM maven:3.9.9-eclipse-temurin-21 AS builder

# Set working directory
WORKDIR /app

# Copy Maven descriptor and download dependencies (layer caching optimization)
COPY pom.xml .
RUN mvn -B dependency:go-offline

# Copy the source code
COPY src ./src

# Package the application (skip tests for faster builds)
RUN mvn clean package -DskipTests

# -------------------------------
# Stage 2: Run the application
# -------------------------------
FROM eclipse-temurin:21-jdk

# Set working directory inside container
WORKDIR /app

# Copy jar from build stage
COPY --from=builder /app/target/distributed.storage-0.0.1-SNAPSHOT.jar app.jar

# Expose application port
EXPOSE 8080

# Set environment variables (optional, can also be overridden by docker-compose or k8s)
ENV SPRING_PROFILES_ACTIVE=prod

# Run the app
ENTRYPOINT ["java", "-jar", "app.jar"]
